[package]
name = "hello-world"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
cf-modkit = { workspace = true }
inventory = { workspace = true }
tracing = { workspace = true }

tokio = { workspace = true }
tokio-util = { workspace = true }
